apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-rbac.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - prometheus.yaml
  - kube-state-metrics.yaml
  - node-exporter.yaml
  - grafana.yaml
  - alertmanager.yaml
  - slack-relay.yaml
